name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks by contributing in this project! If you find something else please, notify'' first issue'
        pr-message: 'Great! Keep that good work. Thanks for supporting'' first pr'
